# Dependencies
markdown: redcarpet
redcarpet:
  extensions: [tables]
exclude: [vendor]
gems:
  - jekyll-sitemap
  - jekyll-feed
# Title of your blog; shows in the header
name: "Mean Elephant"

# Description of your content (will only be used on Google Search)
description: "The internet's #1 Mean Elephant related YouTube channel. Home of ACPG, Going Bananas, Forrest High Weekly and Bad Takes."

# Your name. Will show in your footer + sidebar
author: "Mean Elephant"

url: "http://www.meanelephant.com/"
baseurl: ""

permalink: /blog/:year/:month/:day/:title/

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "Mean Elephant is a relatively new YouTube channel."

# Social Accounts (mine, as placeholders)

twitter: mx3m
github: m3xm
dribbble: m3xm
instagram: m3xm

# Google Analytics (you may want to changes these with yours or even delete :)

#ga_domain: m3xm.github.io
#ga_tracking_id: UA-47727049-1

paginate: 10
paginate_path: "/page/:num"

# SCSS

sass:
  sass_dir: _scss
  style: :compressed
